### ISSUE TITLE
The HTTP server returned error code "0". Only a 2xx response is acceptable: index.php?id=46

### ISSUE THREAD

**Issue by alyainec** [meltingmedia/chimpx#2] opened 2012-01-26 10:31 UTC
While trying to create a new campain on modx 

Error n°: 311
Message: The HTTP server returned error code "0". Only a 2xx response is acceptable: index.php?id=46

any fixes?

Thanks & best regards

**Comment by rtripault** [comment] 2012-01-26 11:25
Hey alyainec,

Thanks for reporting. I'm experiencing the same issue using data center 2 (-us2). Not sure if that DC related, but will inspect that ASAP and report back

**Comment by rtripault** [comment] 2012-01-26 13:11
alyainec,

Could you please confirm that the resource you are trying to use a campaign source is published and publicly web accessible ?

**Comment by alyainec** [comment] 2012-01-26 14:24
hi rtripault,

The resource was published and accessible on the web.

**Comment by rtripault** [comment] 2012-01-26 14:29
Strange…

On my side, was able to create a new campaign. The 2 encountered errors were :

1 - the resource/site was not published
2 - the campaign source resource was site_start (in my case ID 1)

Well, since i'd like to work some more on this component, i'll do some more tests :)

**Comment by alyainec** [comment] 2012-01-26 14:46
rtripault,
do i need to upgrade or re-install my modx 2.1.2 into version 2.2?

**Comment by rtripault** [comment] 2012-01-26 14:50
No, you should not. This component was developed a while ago, so it's supposed to work fine with 2.1.2.

By the way, according to the log, you do not have Friendly URLs enabled, isn't it ? (i know i have not tested chimpx without FURLs)

**Comment by alyainec** [comment] 2012-01-26 14:57
Yeah the FURLs was not enabled as of now because i was using a test server only not on my production server.
I will try to set the FURLs and will let you know what would be the result.

Thanks for your time..

**Comment by alyainec** [comment] 2012-01-26 15:22
rtripault,

It working now, i just did follow your advise. 
Is it  possible  to add in your  component: 
1. Create a list of campaign 
2. Signup email form that will direct saves to the mailchimp subscribers? 

Thanks for your big big help.

**Comment by rtripault** [comment] 2012-01-26 15:36
Glad you got it working :)

For your questions :

1 - AFAIK it's not possible via the MailChimp API, you must first create your list(s) via the MailChimp web app
2 - A snippet is already bundled with chimpx : https://github.com/meltingmedia/chimpx/blob/develop/core/components/chimpx/elements/snippets/chimpxSubscribe.php

If you want to customize the form layout, you might want to check the "demo" chunk https://github.com/meltingmedia/chimpx/blob/develop/core/components/chimpx/elements/chunks/formTpl.tpl

Another option can be to use @bertoost FormIt hook https://github.com/bertoost/MODX-mChimpX

Hope that will help :)
(i'm closing the issue since the problem is "solved").

**Closed as completed by rtripault** 2012-01-26 15:36 UTC
